version: "3.1"

services:
  db:
    image: postgres:10-alpine
    volumes:
      - ./tmp/db-data/pgql:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password123
      POSTGRES_USER: root
      POSTGRES_DB: tes